[package]
name = "sudoku_solver"
version = "0.1.0"
edition = "2024"

[dependencies]
fs = "0.0.5"
serde = "1.0.219"
serde_json = "1.0.140"
csv = "1.3.1"
rstest = "0.25.0"
chrono = "0.4.41"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
dotenv = "0.15.0"

